import type { NewsEvent } from "./types";

export const mockEvents: NewsEvent[] = [
  {
    id: "trump-liberation-day-tariffs-2025",
    title: "Trump Announces Sweeping 'Liberation Day' Reciprocal Tariffs",
    date: "2025-04-03",
    category: "TARIFF",
    summary:
      "A 10% baseline tariff on all imports plus reciprocal rates of 20–49% triggered the worst equity session since the 2020 COVID crash.",
    explanation:
      "On April 2, 2025, the Trump administration unveiled its 'Liberation Day' tariff package: a 10% baseline tariff on virtually all imports, with reciprocal rates of 20–49% targeting countries running large trade surpluses with the US. China's effective rate climbed above 50% when stacked on prior duties. The breadth and speed of implementation caught markets off guard. Equities suffered their worst session since March 2020, with cyclicals and semiconductors leading declines. The dollar paradoxically weakened as traders priced in growth damage and faster Fed cuts, while Treasuries rallied on flight-to-safety bids. Gold initially spiked on the announcement but ended sharply lower as forced liquidations cascaded across even safe-haven positioning — a classic 'sell what you can' tape.",
    assets: [
      {
        symbol: "SPY",
        name: "S&P 500",
        assetType: "INDEX",
        percentChange: -4.84,
        direction: "DOWN",
        openPrice: 564.52,
        closePrice: 537.18,
      },
      {
        symbol: "NQ",
        name: "Nasdaq 100",
        assetType: "INDEX",
        percentChange: -5.97,
        direction: "DOWN",
        openPrice: 19342.5,
        closePrice: 18187.75,
      },
      {
        symbol: "GC",
        name: "Gold",
        assetType: "COMMODITY",
        percentChange: -2.49,
        direction: "DOWN",
        openPrice: 3164.8,
        closePrice: 3086.0,
      },
      {
        symbol: "DXY",
        name: "US Dollar Index",
        assetType: "FOREX",
        percentChange: -1.67,
        direction: "DOWN",
        openPrice: 103.85,
        closePrice: 102.12,
      },
      {
        symbol: "BTC",
        name: "Bitcoin",
        assetType: "CRYPTO",
        percentChange: -3.14,
        direction: "DOWN",
        openPrice: 86840,
        closePrice: 84112,
      },
    ],
  },
  {
    id: "cpi-january-2025-hot",
    title: "January CPI Surprises Hot at 3.0% YoY",
    date: "2025-02-12",
    category: "INFLATION",
    expectedValue: "2.9%",
    actualValue: "3.0%",
    summary:
      "Headline inflation reaccelerated for the fourth straight month, derailing the Fed's near-term rate-cut narrative.",
    explanation:
      "January 2025 CPI printed at 3.0% YoY versus 2.9% consensus, with core CPI at 3.3% versus 3.1% expected. The headline marked a fourth consecutive monthly reacceleration, with sticky services components (transportation, shelter) overwhelming continued goods disinflation. Egg prices surged on bird-flu supply disruption, though the Fed traditionally looks past food volatility. The bigger concern was supercore — services ex-housing — which jumped sharply. Treasuries sold off across the curve, with the 10Y yield climbing roughly 10bps. Fed funds futures repriced from three cuts in 2025 to closer to one. Equities fell modestly while gold drifted lower as real yields jumped, breaking its typical inflation-hedge correlation.",
    assets: [
      {
        symbol: "SPY",
        name: "S&P 500",
        assetType: "INDEX",
        percentChange: -1.07,
        direction: "DOWN",
        openPrice: 605.3,
        closePrice: 598.83,
      },
      {
        symbol: "TLT",
        name: "20+ Yr Treasury ETF",
        assetType: "STOCK",
        percentChange: -1.42,
        direction: "DOWN",
        openPrice: 88.21,
        closePrice: 86.96,
      },
      {
        symbol: "GC",
        name: "Gold",
        assetType: "COMMODITY",
        percentChange: -0.42,
        direction: "DOWN",
        openPrice: 2902.4,
        closePrice: 2890.2,
      },
      {
        symbol: "NQ",
        name: "Nasdaq 100",
        assetType: "INDEX",
        percentChange: -1.31,
        direction: "DOWN",
        openPrice: 21786.5,
        closePrice: 21501.0,
      },
    ],
  },
  {
    id: "fomc-march-2025-hold",
    title: "Fed Holds Rates Steady, Maintains Two-Cut 2025 Outlook",
    date: "2025-03-19",
    category: "FED",
    summary:
      "The FOMC kept rates at 4.25–4.50% and reaffirmed two cuts this year despite tariff-driven inflation risks. Risk assets rallied.",
    explanation:
      "The FOMC unanimously held the federal funds rate at 4.25–4.50% for a second straight meeting. The updated Summary of Economic Projections raised 2025 inflation forecasts and trimmed growth expectations, but the median dot plot still penciled in two 25bp cuts before year-end — a more dovish outcome than feared. Powell repeatedly characterized tariff-driven price increases as likely transitory, signaling that the bar for cuts remained intact. The committee also slowed quantitative tightening, capping monthly Treasury runoff at $5B from $25B — a quietly dovish technical adjustment that lowered net Treasury supply and supported duration. Risk assets rallied broadly: the S&P closed up over 1%, bitcoin surged nearly 5%, and small caps outperformed on relief that rate sensitivity would ease.",
    assets: [
      {
        symbol: "SPY",
        name: "S&P 500",
        assetType: "INDEX",
        percentChange: 1.08,
        direction: "UP",
        openPrice: 562.1,
        closePrice: 568.18,
      },
      {
        symbol: "BTC",
        name: "Bitcoin",
        assetType: "CRYPTO",
        percentChange: 4.59,
        direction: "UP",
        openPrice: 82380,
        closePrice: 86162,
      },
      {
        symbol: "IWM",
        name: "Russell 2000",
        assetType: "INDEX",
        percentChange: 1.62,
        direction: "UP",
        openPrice: 202.45,
        closePrice: 205.73,
      },
      {
        symbol: "GC",
        name: "Gold",
        assetType: "COMMODITY",
        percentChange: 0.36,
        direction: "UP",
        openPrice: 3030.4,
        closePrice: 3041.3,
      },
    ],
  },
];
