// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations and other CLI operations must use Neon's DIRECT endpoint —
    // Prisma takes advisory locks, which are unreliable through the pooled
    // (PgBouncer transaction-mode) endpoint. Falls back to DATABASE_URL so a
    // single-URL setup still works.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
